name: Build HTTPD Project Image

on:
  pull_request:
    paths:
      - "httpd-project/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build HTTPD Docker image
        run: |
          docker build -t my-httpd-project ./httpd-project
