name: Build NGINX Project Image
run-name: Build and push NGINX Image • ${{ github.repository }} ∷ ${{ github.ref }} to ghcr.io

on:
  push:
    branches:
      - feature/update-nginx-index-hml
    paths:
      - "nginx-project/**"
  # pull_request:
  #   paths:
  #     - "nginx-project/**"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Git commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up QEMU for multi-architecture support
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx-project
          file: ./nginx-project/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/nginx-project:test
            ghcr.io/${{ github.repository }}/nginx-project:${{ env.sha_short }}
          build-args: |
            TARGETPLATFORM=linux/arm64
          labels: |
            org.opencontainers.image.licenses=MIT

      - name: Display Docker image info
        run: |
          docker manifest inspect ghcr.io/${{ github.repository }}/nginx-project:${{ env.sha_short }}
