name: Build HTTPD Project Image

on:
  push:
    branches:
      - main
    paths:
      - "httpd-project/**"
  # pull_request:
  #   paths:
  #     - "httpd-project/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Git commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build HTTPD Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/httpd-project:latest \
                       -t ghcr.io/${{ github.repository_owner }}/httpd-project:${{ env.sha_short }} \
                       ./httpd-project

      - name: Push HTTPD Docker images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/httpd-project:latest
          docker push ghcr.io/${{ github.repository_owner }}/httpd-project:${{ env.sha_short }}
