name: Build NGINX Project Image

on:
  push:
    branches:
      - main
    paths:
      - "nginx-project/**"
  # pull_request:
  #   paths:
  #     - "nginx-project/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Git commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build NGINX Docker image
        run: |
          docker build -t my-nginx-project:latest -t my-nginx-project:${{ env.sha_short }} ./nginx-project
